version: "3.0"
services:
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - "discovery.type=single-node"
    networks:
      - local-net
    ports:
      - 9200:9200
  kibana:
    container_name: kibana01
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - local-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  local-net:
    driver: bridge